# Message displayed on startup
message: Hello, world!

# You should probably make this 'true'
run: true

# Control port
control_port: 18333

# IRC control configuration
irc:
    server: irc.freenode.net
    port: 6667
    nick: <%= compd_nick %>
    user: <%= compd_user %>
    gecos: Compd Controller
    channel: "#srobo-comp-ops"
    enable: true

# Redis server configuration
# The redis server is run by compd
# so don't change these unless you know what you are doing
redis:
    host: localhost
    port: 10056
    db: 0
    # Okay, you can change this one
    server: /usr/sbin/redis-server
